### ISSUE TITLE
Possible memory leak when reloading script

### ISSUE THREAD

**Issue by End-of-Eternity** [Endilll/vapoursynth-preview#15]
Steps to replicate:

- Press CTRL+R
- Profit
- Realise that buying more ram was not the solution
- Loss

It appears that, upon reloading, some buffer isn't flushed, and all ram that was in use by vapoursynth-preview isn't freed. This therefore starts to cause problems after multiple refreshes, where vapoursynth-preview can end up using all of my system memory. I have tried (though only for a little bit) to find the source of the problem, though I'm unsure exactly where it could be. This has been an issue on all systems I've tested in the last few months, both unix based (arch) and Windows, at current git head.

I will do some more work to try to trace the issue when I have time.

Cheers

**Comment by Endilll** [comment]
That's a known bug (or I'd say a limitation of current VS wrapper for Python) that I may be able fix with the next release of VS, since I see changes to the relevant part of the wrapper.

Or I'm just dumb and haven't realized how to implement this properly. It's really a pity that VSP can't deliver on the key feature it've been developing in mind with.

**Comment by Endilll** [comment]
I'm quite happy to close this issue as resolved.
